# **Install & Load Dataset**



In [ ]:
!pip install datasets

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split = 'train')

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})


In [ ]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rat

# **DataFrame Creation**

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(dataset)

In [ ]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [ ]:
df = df[ ['title' , 'abstract'] ]

In [ ]:
df.shape

(15000, 2)

In [ ]:
df = df.head(15000)

In [ ]:
df.shape

(15000, 2)

In [ ]:
df.isnull().sum()

,0
title,0
abstract,0


In [ ]:
df["paper_text"] = df["title"] + " " + df["abstract"]

In [ ]:
df["paper_text"].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [ ]:
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [ ]:
type(df["paper_text"].iloc[0])

str

# **SentenceTransformer**

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [ ]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ",regex=False)

In [ ]:
df["paper_text"] = df["paper_text"].str.strip()

# **Embedding [of 1]**

In [ ]:
sample_text = df["paper_text"].iloc[0]

In [ ]:
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [ ]:
embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)


In [ ]:
embedding[:56]

array([-0.1315641 , -0.00678266, -0.00367612,  0.03265158,  0.11219642,
        0.01227267,  0.09816719, -0.0900523 ,  0.04231161, -0.01977348,
       -0.03308417,  0.07452948,  0.10632038, -0.02060429, -0.02052106,
        0.00169493,  0.07081953,  0.05854454, -0.11231912,  0.02082474,
        0.05692544,  0.0201578 ,  0.0258311 ,  0.0321703 ,  0.10513764,
       -0.09676763,  0.02700802, -0.0234509 , -0.04549678, -0.01013699,
       -0.01794855, -0.04814427,  0.01077652, -0.03759069,  0.01943481,
        0.03715189,  0.02967844,  0.04330941,  0.04373213,  0.03704866,
       -0.00182594,  0.00455183, -0.00799067,  0.03037368, -0.014378  ,
        0.03795147,  0.0595916 , -0.02583356, -0.06521576,  0.05900268,
       -0.02107134,  0.07359422, -0.05720106,  0.00294061,  0.00767515,
       -0.0333416 ], dtype=float32)

# **Embedding [of 5]**

In [ ]:
sample_of_5_embedding = model.encode(df["paper_text"].head(5).to_list())

In [ ]:
print(sample_of_5_embedding.shape)

(5, 384)


In [ ]:
sample_of_5_embedding

array([[-0.1315641 , -0.00678266, -0.0036761 , ...,  0.09561252,
        -0.04423944,  0.00522624],
       [-0.03589668, -0.06343269, -0.00394966, ...,  0.07206137,
        -0.13262011, -0.00412079],
       [-0.08129284,  0.024103  , -0.08868261, ..., -0.04524419,
        -0.0476585 , -0.01549932],
       [-0.10218991, -0.06282566,  0.03273673, ..., -0.03118814,
         0.03174181,  0.03621249],
       [-0.08391042,  0.01838467, -0.01556663, ..., -0.01188403,
        -0.10644462,  0.00790998]], dtype=float32)

# **Cosine Similarity [of 5]**

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[0].reshape(1, -1))
print(similarity)

[[1.0000001]]


In [ ]:
similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]


In [ ]:
for i in range(0,5):
  sim  = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1), sample_of_5_embedding[i].reshape(1, -1))
  print(sim)

[[1.0000001]]
[[0.36625272]]
[[0.33522844]]
[[0.15505108]]
[[0.37421533]]


# **FAISS [of 5]**

In [ ]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 33.7 MB/s eta 0:00:00


In [ ]:
import faiss

In [ ]:
faiss.normalize_L2(sample_of_5_embedding)

In [ ]:
index = faiss.IndexFlatIP(384)

In [ ]:
print(index.ntotal)

0


In [ ]:
index.add(sample_of_5_embedding)

In [ ]:
print(index.ntotal)

5


In [ ]:
query = "deep learning for medical image analysis"

In [ ]:
query_embedding = model.encode(query)
query_embedding.shape

(384,)

In [ ]:
query_embedding.reshape(1,-1)

array([[-3.52526233e-02,  5.43267392e-02,  5.65811694e-02,
        -4.97096516e-02, -3.52174975e-02, -2.67348643e-02,
        -8.23498983e-03,  1.52610382e-02, -1.31555051e-02,
        -5.45782186e-02, -5.26165627e-02, -1.20118475e-02,
        -8.10011625e-02,  9.73842591e-02, -1.15813181e-01,
        -1.68417636e-02, -9.74307284e-02, -5.52448351e-03,
        -1.06863692e-01,  7.64734065e-03, -4.89181019e-02,
        -6.45619398e-03, -3.65177542e-02,  2.23113876e-02,
         5.65221906e-02,  4.34993301e-03,  6.29342273e-02,
        -1.09063022e-01,  3.48554738e-02, -1.03746569e-02,
         7.24759325e-02, -3.63332927e-02,  1.78154279e-02,
         1.52815776e-02,  4.68111634e-02,  7.27785826e-02,
        -1.72747560e-02,  5.71634062e-02,  6.73012529e-03,
         2.91874819e-02,  4.84563038e-02,  5.15045710e-02,
         3.13240252e-02,  5.97999133e-02,  8.63463730e-02,
        -1.21598854e-03,  3.83908153e-02, -1.21436063e-02,
         5.59613332e-02,  9.04098302e-02, -1.46837337e-0

In [ ]:
query_embedding.shape

(384,)

In [ ]:
query_embedding = model.encode([query])
query_embedding.shape

(1, 384)

In [ ]:
faiss.normalize_L2(query_embedding)

In [ ]:
D, I = index.search(query_embedding, 5)

In [ ]:
print(D)
print(I)

[[0.24243258 0.17442387 0.14026146 0.07622977 0.01298682]]
[[3 4 0 2 1]]


# **Embedding [of all 15000]**

In [ ]:
import os
import numpy as np

if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings...")
    embeddings = np.load("paper_embeddings.npy")

else:
    print("Generating embeddings...")
    embeddings = model.encode(df["paper_text"].to_list() , batch_size=32 , show_progress_bar=True)
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings...


In [ ]:
print(embeddings.shape)
print(type(embeddings))
embeddings.dtype

(15000, 384)
<class 'numpy.ndarray'>


dtype('float32')

# **FAISS [of 15000]**

In [ ]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index...")
    index = faiss.read_index("paper_faiss.index")

else:
    print("Creating new FAISS index...")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)

    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index...


In [ ]:
print(index.ntotal)

15000


In [ ]:
query = "deep learning for medical image analysis"
query_embedding = model.encode([query])
query_embedding.shape
faiss.normalize_L2(query_embedding)
D, I = index.search(query_embedding, 5)
print(D) # Similarity Score
print(I) # Indices

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]


In [ ]:
df.iloc[10466]["title"]

A Perspective on Deep Imaging


In [ ]:
df.iloc[10466]["abstract"]

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.



In [ ]:
df.iloc[11873]["title"]

'Classification of MRI data using Deep Learning and Gaussian\n  Process-based Model Selection'

In [ ]:
df.iloc[11873]["abstract"]

'  The classification of MRI images according to the anatomical field of view is\na necessary task to solve when faced with the increasing quantity of medical\nimages. In parallel, advances in deep learning makes it a suitable tool for\ncomputer vision problems. Using a common architecture (such as AlexNet)\nprovides quite good results, but not sufficient for clinical use. Improving the\nmodel is not an easy task, due to the large number of hyper-parameters\ngoverning both the architecture and the training of the network, and to the\nlimited understanding of their relevance. Since an exhaustive search is not\ntractable, we propose to optimize the network first by random search, and then\nby an adaptive search based on Gaussian Processes and Probability of\nImprovement. Applying this method on a large and varied MRI dataset, we show a\nsubstantial improvement between the baseline network and the final one (up to\n20\\% for the most difficult classes).\n'

# **Search [return]**

In [ ]:
def search_paper_return(query, k=5):
  # Generate query embedding
  query_embedding = model.encode([query])

  # Normalize query embedding
  faiss.normalize_L2(query_embedding)

  # Search in FAISS index
  D, I = index.search(query_embedding, k)

  return D, I

In [ ]:
D , I = search_paper_return("deep learning for medical image analysis")
print(D)
print(I)

[[0.6807244  0.67092204 0.65219975 0.62811744 0.61311525]]
[[10466 13730 11873 12691 11282]]


# **Search [display - zip()]**

In [ ]:
def search_paper_display(query, k = 5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0] , I[0]), start = 1):
      print()
      print("=" * 100)
      print()
      print(f"Result Rank        : #{rank}")

      print(f"Paper Index        : {idx}")

      print(f"Similarity Score   : {score:.4f}")

      print(f"\nTitle: {df.iloc[idx]['title']}")

      print(f"\nAbstract: {df.iloc[idx]['abstract'][:500]}")

In [ ]:
search_paper_display("deep learning for medical image analysis")



Result Rank        : #1
Paper Index        : 10466
Similarity Score   : 0.6807

Title: A Perspective on Deep Imaging

Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance


Result Rank        : #2
Paper Index        : 13730
Similarity Score   : 0.6709

Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?

Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure 

# **Summarize [BART]**

In [ ]:
!pip install transformers==4.46.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 88.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 44.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 92.4 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.20.1
    Uninstalling huggingface_hub-1.20.1:
      Successfully uninstalled huggingface_hub-1.20.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.1
    Uninstalling transformers-5.12.1:
      Successfully uninstalled transformers-5.12.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the

In [ ]:
from transformers import pipeline

In [ ]:
summarizer = pipeline("summarization" , model = "facebook/bart-large-cnn")

KeyError: "Unknown task summarization, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [ ]:
type(summarizer)

NameError: name 'summarizer' is not defined

In [ ]:
summary = summarizer(df.iloc[10466]["abstract"] , max_length = 120  ,min_length = 40)

In [ ]:
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]


In [ ]:
type(summary)

In [ ]:
type(summary[0])

In [ ]:
summary[0]["summary_text"]

# **Search + Summarize**

In [ ]:
def search_and_summarize(query, k=5):

  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)

  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]) , start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print(f"\nTitle:")
    print(df.iloc[idx]["title"])

    print(f"\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    # Generate summary
    summary = summarizer(df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)

    print("\nSummary:")
    print(summary[0]["summary_text"])
    print("\n")

In [ ]:
search_and_summarize("Deep learning in medical imaging" , k = 5)

# **Keyword**

In [ ]:
!pip install keybert

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.4/41.4 kB 1.9 MB/s eta 0:00:00


In [ ]:
from keybert import KeyBERT

ModuleNotFoundError: No module named 'keybert'

In [ ]:
kw_model = KeyBERT(model)

In [ ]:
type(kw_model) # model = SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [ ]:
text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

In [ ]:
print(keywords)

[('imaging', 0.4528), ('tomographic', 0.4488), ('reconstruction', 0.3623), ('deep', 0.3003), ('learning', 0.2622)]


In [ ]:
print(type(keywords))

<class 'list'>


In [ ]:
print(type(keywords[0]))

<class 'tuple'>


In [ ]:
keywords = kw_model.extract_keywords(text , keyphrase_ngram_range = (1, 3) , stop_words = "english")

In [ ]:
print(keywords)

[('tomographic imaging deep', 0.6704), ('imaging deep learning', 0.6543), ('learning medical imaging', 0.6041), ('imaging deep', 0.5919), ('medical imaging', 0.5281)]


# **Search + Summarize + Keyword**

In [ ]:
def search_summarize_keywords(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]), start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print("\nTitle:")
    print(df.iloc[idx]["title"])

    print("\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    print()

    # Generate summary
    summary = summarizer( df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)
    print("Summary:")
    print(summary[0]["summary_text"])
    print()

    # Extract keywords from the abstract
    keywords = kw_model.extract_keywords( df.iloc[idx]["abstract"] , keyphrase_ngram_range = (1, 3), stop_words = "english")

    print("Keywords:")

    for keyword, score in keywords:
      print(keyword)
    print("\n")

In [ ]:
search_summarize_keywords("natural language processing using transformers", k = 5)



Result Rank        : #1
Paper Index        : 3677
Similarity Score   : 0.5540

Title:
Category-Theoretic Quantitative Compositional Distributional Models of
  Natural Language Semantics

Abstract Preview:
  This thesis is about the problem of compositionality in distributional
semantics. Distributional semantics presupposes that the meanings of words are
a function of their occurrences in textual contexts. It models words as
distributions over these contexts and represents them as vectors in high
dimensional spaces. The problem of compositionality for such models concerns
itself with how to produce representations for larger units of text by
composing the representations of smaller units of text.

Summary:
This thesis is about the problem of compositionality in distributional purposefullysemantics. It uses the categorical framework developed by Coecke, Sadrzadeh, and Clark. It shows how this approach can be practically implemented to produce concrete distributional models.

Keywords:

# **Here NLP concludes!!!**
   

